name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main  # Change this to your default branch if it's not 'main'

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'  # Use Node.js 20

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: List build output
        run: |
          echo "Contents of dist directory:"
          ls -la ./dist
          echo "Contents of dist/assets directory:"
          ls -la ./dist/assets

      - name: Verify gh-pages branch before deployment
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          echo "Contents of gh-pages branch before deployment:"
          ls -la

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist

      - name: Verify gh-pages branch after deployment
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          echo "Contents of gh-pages branch after deployment:"
          ls -la